### ISSUE TITLE
l10n: Adding Turkish in mintlocale automatically adds Italian, which can't be removed

### ISSUE THREAD

**Issue by gunerc** [linuxmint/mint22-beta#151] opened 2024-07-10 14:57 UTC
Hello,

My Mint22 Beta system language is En-US, and keyboard/region/time language is Turkish. When I add Turkish language support files via System Settings' Language Settings GUI, Italian-Itally language support and its related files are added automatically too unwantedly. Afterwards when I click Remove button to uninstall Italian-Italy language in GUI, it does not work, it is not removed.

Then I manually unistall all Italian related language files manuall by cli:

guner@hpg62:~/Desktop$ sudo apt purge hunspell-it hyphen-it language-pack-gnome-it language-pack-it libreoffice-help-it libreoffice-l10n-it mythes-it witalian language-pack-gnome-it-base language-pack-it-base hunspell-it

However, after removal, Italian language support still remains appearing in Install / Remove Languages' GUI.

Would this be corrected: no addition of Italian language support when Turkish is added and it can be removed and not remain via/in GUI.

Kind Regards.
![Screenshot from 2024-07-10 17-51-01](https://github.com/linuxmint/mint22-beta/assets/175225807/be23f056-38eb-4277-9b02-1b0f6c49f999)

**Comment by clefebvre** [comment] 2024-07-19 08:12
I'm pretty sure this is upstream from us and specific to Ubuntu and their language-pack.. I'll try to find more info.

**Comment by clefebvre** [comment] 2024-07-19 09:35
The postinst for the language pack calls locale-gen.

Locale-gen doesn't just generate TR_CY, it also generates TR_CY which collides with IT_IT, see the hash collision here:

![image](https://github.com/user-attachments/assets/54001d7c-a9db-4837-aa97-d4f95b34af96)

This has been observed for years in Ubuntu. Here's an example: 

https://ubuntuforums.org/showthread.php?t=1652079

I don't think it's a bug per se, I think it's by design. Ubuntu completely redesigned the way locales work and deviated from Debian to introduce the notion of language packs, i.e. the grouping of different locales under the same packs.

What you're seeing here are unwanted links between locales. It doesn't just bring Italian via Turkish-Cyprus, it can bring a multitude of locales closely or remotely related to your installed locales.

I'll close this now since it's upstream from us.

**Closed as completed by clefebvre** 2024-07-19 09:35 UTC
