### ISSUE TITLE
Time synchronization problem in MATE and Xfce

### ISSUE THREAD

**Issue by billyswong** [linuxmint/mint22-beta#51] opened 2024-07-02 10:06 UTC
The regression in fact originated from Mint 21.3, with the silent replacement of package `ntp` with `systemd-timesyncd`, with no announcement anywhere. The handling was far from ideal, with a lot of people losing time-synchronization unknowingly when they perform in-place upgrade. The lack of announcement about this change may also be why it missed the 21.3 beta bug founding.
https://github.com/linuxmint/ubiquity/issues/73

But with Mint 22 coming of age, we should at least fix some of the easiest to fix part of this pile of problems caused by that change.
https://github.com/linuxmint/linuxmint/issues/644
The `time-admin` command is still relying on reading status of `ntp`, but `mate-time-admin` is reading status from `systemd-timesyncd`. So if we point the "Time and Date" menu entry to utilize the MATE offering instead, we can at least solve the GUI confusion in new MATE installation.

I am not sure how it should be best done for Xfce users, but for the worst case where "no time to fix this problem, sorry", please at least provide some information in release notes as a known problem with instruction on how to get/set the time and time-synchronization setting correctly. In current status, it just looks broken.

**Comment by clefebvre** [comment] 2024-07-02 17:02
`ntp` and `ntpdate` were in Mint until version 21.2 (included). They're not in 21.3, 22, Xubuntu or Ubuntu MATE (any versions).

`systemd-timesync` is everywhere (Mint, Xubuntu, Ubuntu MATE).

`ntp` and `systemd-timesync` both provide `time-daemon` and conflict with one another. We can't ship with both.

**Comment by billyswong** [comment] 2024-07-03 10:09
> `ntp` and `systemd-timesync` both provide `time-daemon` and conflict with one another. We can't ship with both.

Thanks for explanation. I think most users don't mind the backend change as long as the time synchronization works and it is presented in GUI correctly. Systemd haters are not going to use Mint in the first place. (Ideally it will be best if the GUI let one see and switch the time server. But that's a far more minor technicality.)

I read some users in forum after a bunch of trial and errors ended up reinstalling `ntp` in Mint 21.3 MATE/Xfce to restore the time synchronization. So the upcoming Mint 22 upgrade program may still need to handle the time-daemon switching transition, this time with possibilities of
1) `ntp` up and running
2) nothing up and running properly, in various form of breakage
3) time synchronization is not applying because of the users' explicit request
4) `systemd-timesync` up and runnning, nothing to do hurray

Even just a shrove of everyone into situation 4 will be better than the status quo.

**Comment by BellavGFH** [comment] 2024-07-04 06:57
@billyswong: For what it's worth, I can confirm from the install of my other boxen (Xubuntu 22.04 LTS and Debian 12 xfce) that was indeed an issue, and the best fix you mention does solve it:

![Screenshot_2024-07-04_08-38-19](https://github.com/linuxmint/mint22-beta/assets/170173108/a737455f-7e2f-4ea7-83cf-37f408e7611c)

**Comment by billyswong** [comment] 2024-07-04 08:26
@BellavGFH So time synchronization is broken, or at least partially broken, in Xubuntu 22.04 LTS too?

**Comment by BellavGFH** [comment] 2024-07-04 10:17
@billyswong I suppose "broken" is one way of putting it. As I mentioned, I see/ saw similar on Xubuntu since 22.04 and also Debian BW. It looks like a conflict between `ntp` and `systemd-timesyncd.service`, where the latter is aggressive, "breaks" things, and then in many cases not functions properly IRL, as Clem also mentions here.
For us, solution was to `sudo systemctl disable systemd-timesyncd.service` and run `ntp` as before without issues.
More info:
[https://linuxreviews.org/HOWTO_ensure_your_clock_is_accurate_and_showing_the_correct_time_using_the_Network_Time_Protocol](url)

**Comment by clefebvre** [comment] 2024-07-04 18:29
In MATE, mate-time-admin (from mate-control-center) works fine with systemd-timesync. Note that this is hidden in Mint though because gnome-system-tools is needed for shares and users, and both packages provide a time tool. Incidently, Xfce doesn't, so the one from gnome-system-tools is needed here.

![image](https://github.com/linuxmint/mint22-beta/assets/1138515/8088e412-f9f0-4bfe-82ee-4c5ee3dc6b5f)

I think we'll patch gnome-system-tools and make it work with systemd-timesyncd.

**Comment by BellavGFH** [comment] 2024-07-05 11:28
@clefebvre As long as it works™! ;)
FYI: in 9 out of 10 times we install "Users and Groups" (aka `gnome-system-tools`) on Debian xfce because it's not included there. Xubuntu however does have it default. In both cases `ntp` runs perfectly fine.

**Comment by clefebvre** [comment] 2024-07-06 11:49
Fixed in gnome-system-tools 3.0.0+mint1

**Closed as completed by clefebvre** 2024-07-06 11:49 UTC
Labels: bug

**Comment by billyswong** [comment] 2024-07-06 15:22
@clefebvre 

Q1. Will the patched gnome-system-tools be published as a github repository or somewhere else? Is this patched version going to support both time daemons or only systemd-timesyncd?
Q2. Any mintupgrade update required or planned for the time daemon change?

**Comment by clefebvre** [comment] 2024-07-18 15:18
It's available at https://gitlab.com/linuxmint/pins/mint/gnome-system-tools. We use commits, but you can consider this a patch, it's not a fork per se, just a patched version for now.

No update mechanism required for this since it's just a version update.

**Comment by billyswong** [comment] 2024-07-18 23:53
@clefebvre for Q2, I was referring to users who seem to find their computers NOT running any one of the time daemon after in-place upgrade https://forums.linuxmint.com/viewtopic.php?t=416317
