### ISSUE TITLE
Uninstalling flatpaks from menu doesn't work in Cinnamon 

### ISSUE THREAD

**Issue by MattEqualsCoder** [linuxmint/mint22-beta#63] opened 2024-07-03 01:22 UTC
I've restarted just to see if it would help, but still seems to be an issue. If I open the menu in Cinnamon and right click on a flatpak installed application and go to uninstall, it doesn't seem to do anything. This doesn't appear to be the case for non-flatpak apps.

**Comment by haggen88** [comment] 2024-07-03 01:43
#13 related

**Comment by Angedestenebres** [comment] 2024-07-03 17:13
Hey :cat: 

In fact, there is a python action launched in the background but the process stops and sticks there:

![VirtualBox_Linux Mint 22_03_07_2024_19_07_14](https://github.com/linuxmint/mint22-beta/assets/21110485/5230fa5b-1758-4643-a1e8-658d8bf47ff4)

Anyway, this is a bug and you are right, for deb applications, it still works ;)

**Comment by mtwebster** [comment] 2024-07-03 17:41
duplicate of #13

**Closed as completed by mtwebster** 2024-07-03 17:41 UTC
