### ISSUE TITLE
xed: Untitled Document zero bye size not recognized (regression since 21.3)

### ISSUE THREAD

**Issue by Harry-W-Haines-III** [linuxmint/mint22-beta#26] opened 2024-06-30 23:05 UTC
In Linux Mint 21.3 Cinnamon, in a folder like Downloads, if you right click, create new document, select "Empty Document" and use the highlighted name "Empty Document",  you can then open it with Xed even though it is a 0 byte file as a Type (text/plain).  It has always been this way for years.  See properties screen shot below:

![Screenshot from 2024-06-30 22-58-19](https://github.com/linuxmint/mint22-beta/assets/45599505/30f63d8e-4b44-4f3a-8c43-1c953fe034f0)

When I do the same thing in Linux Mint 22 Beta, there is a different behavior.  It says "Unknown file type" when you try to open the file you just created.  See the properties screen shot below:

![Screenshot from 2024-06-30 19-03-10](https://github.com/linuxmint/mint22-beta/assets/45599505/cfdd356d-a173-4e57-acd1-22ceb93a9f2a)

Did something change with the desktop standard/MIME or this a Linux Mint issue?
Please advise.

**Comment by Harry-W-Haines-III** [comment] 2024-07-02 17:15
clefebvre  Has anyone had a chance to look at this one yet?

**Comment by Harry-W-Haines-III** [comment] 2024-07-02 23:54
https://github.com/clefebvre  Has anyone had time to look at this?

**Comment by clefebvre** [comment] 2024-07-04 09:15
If that's a change in the upstream package base (mime or whatever) Xed could handle application/x-zerosize...

if it's a regression in Nemo (which provides that action/template), then it should be fixed there instead.

**Comment by Harry-W-Haines-III** [comment] 2024-07-06 21:32
@ [clefebvre](https://github.com/clefebvre)  I am unable to locate the commit that may have caused the regression in nemo (6.2.0) wilma.  nemo-action.c?

**Comment by Harry-W-Haines-III** [comment] 2024-07-06 23:22
gio: Change content type of zero-sized files to application/x-zerosize
https://gitlab.gnome.org/GNOME/glib/-/merge_requests/3053

**Comment by Harry-W-Haines-III** [comment] 2024-07-07 00:10
So it is an upstream change in GIO and it wasn't noticed until the 24.04 rebase.
Used the command "gio mime application/x-zerosize xed.desktop" to address the issue.

**Comment by billyswong** [comment] 2024-07-07 03:12
Hi @Harry-W-Haines-III you found a working workaround for yourself. But has it been implemented in upcoming LM 22? This bug is affecting Cinnamon + MATE + Xfce. "Text Editor" in preferred applications no longer handle zero-sized newly created empty documents automatically. Manually assigning xed to open application/x-zerosize isn't a proper solution.

Edit: I propose re-opening this bug, until Mint devs confirm they have resolved the issue on their side.

**Comment by Harry-W-Haines-III** [comment] 2024-07-07 12:58
@clefebvre Re opened for Mint Developer's consideration on how to handle this issue affecting all three desktop editions.

**Comment by Harry-W-Haines-III** [comment] 2024-07-07 16:26
Looking at GNOME 46, Nautilus was modified not to allow creation of any new documents that did not exist in the "Templates" folder.  Placing a zero byte file "Empty Document.txt" in the "Templates" folder aligns with what the GNOME developers intended when the change was made to GIO.

**Comment by billyswong** [comment] 2024-07-08 09:01
Alternative resolution taken by lxqt, posted here for reference
https://github.com/lxqt/lxqt/discussions/2395#discussioncomment-5353272

**Comment by mtwebster** [comment] 2024-07-08 16:38
Can someone try creating a file called `test-x-zerosize.xml` (or really anything with the .xml extension) and paste this in:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
   <mime-type type="application/x-zerosize">
     <_comment>Empty text file</_comment>
     <generic-icon name="text-x-generic"/>
     <sub-class-of type="text/plain"/>
   </mime-type>
</mime-info>
```

Copy it into /usr/share/mime/packages:
```
sudo cp test-x-zerosize.xml /usr/share/mime/packages/
```
then update the mime database:
```
sudo update-mime-database /usr/share/mime
```

This should make these 0-length files use the correct icon and open as a text file.

* To undo this, remove that file, then re-run the update-mime-database command

**Comment by Harry-W-Haines-III** [comment] 2024-07-08 16:42
@mtwebster   You are fantastic !!  It works !!
![image](https://github.com/linuxmint/mint22-beta/assets/45599505/eeefc385-d55d-4380-89ab-4b5a057774af)

**Comment by billyswong** [comment] 2024-07-09 01:52
@mtwebster Yes it works in MATE. The "Preferred Applications" > System > Text Editor now also auto redirect what to open empty files alongside normal text files.

**Comment by Harry-W-Haines-III** [comment] 2024-07-09 12:37
I'm satisfied the issue is resolved.  Do not want to close the report just yet until the others who have commented have agreed with the solution.

**Comment by mtwebster** [comment] 2024-07-09 13:10
I'm just exploring solutions for now - the xml file looks most promising but it would end up being Mint-only.

**Comment by Harry-W-Haines-III** [comment] 2024-07-09 13:14
I thought that your's  was an elegant solution because it didn't require modifying Nemo or touching any of the libraries as other distros have proposed.

**Comment by mtwebster** [comment] 2024-07-12 13:36
So we decided against modifying the mimetype definition for now, as it would only address things in Mint. Instead we've:

- [Modified xed](https://github.com/linuxmint/xed/commit/3239b902a546f124faa49d49ff474b7f5347267a) to let it know it can open x-zerosize files (this will prevent having to 'Open with...' and fix it yourself). Presumably other editors will do the same.
- [Modified nemo](https://github.com/linuxmint/nemo/commit/7c67dc922c5924edd4de5f414d87eb9eb28b852a) so 'Create New Document -> Empty Document' will create a 1 byte file (containing newline). The file will behave no differently in a text editor, since a newline is automatically added to the end of a text file when saving it.

We'll keep an eye upstream to see if anything happens regarding this whole ordeal.

**Closed by mtwebster** 2024-07-12 13:36 UTC
