### ISSUE TITLE
l10n: Wrong German Localization in software manager settings 

### ISSUE THREAD

**Issue by dohst123** [linuxmint/mint22-beta#144] opened 2024-07-10 07:13 UTC
1. Open software manager ("Anwendungsverwaltung" in German)
2. Goto hamburger menu and click on settings ("Einstellungen" in German)
3. To settings page opens - most of setting options are in English and not in German (see screenshot).

![Bildschirmfoto vom 2024-07-10 09-09-51](https://github.com/linuxmint/mint22-beta/assets/61592324/323030b4-31e0-4c48-9a03-79e8e3f48f83)

**Comment by Angedestenebres** [comment] 2024-07-10 12:48
Duplicate of https://github.com/linuxmint/mint22-beta/issues/37 :wink:

**Closed as completed** 2024-07-18 17:17 UTC
