### ISSUE TITLE
Enabling virtual 3D Acceleration

### ISSUE THREAD

**Issue by iamdtms** [linuxmint/mint22-beta#85] opened 2024-07-04 10:36 UTC
Enable 3D Acceleration couses freezy after some click on the desktop.

Environment:
- Virtualbox 7.0.18
- Nvidia GTX 1650

Which graphics controller fits well for this virtual environment?

Thank you. 

![Screenshot 2024-07-04 123223](https://github.com/linuxmint/mint22-beta/assets/11964785/54f3b09e-e616-40b8-9b16-4d6198b08af9)

**Comment by clefebvre** [comment] 2024-07-04 12:34
I use the following settings:

![image](https://github.com/linuxmint/mint22-beta/assets/1138515/55a50df0-37a7-4f6a-8847-fbcf73f4fb29)

**Comment by clefebvre** [comment] 2024-07-04 12:34
I'll close this though since it's not a bug we can work on.

**Closed as completed by clefebvre** 2024-07-04 12:34 UTC
