### ISSUE TITLE
iso: Memtest86+ in GRUB menu

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/mint22-beta#17] opened 2024-06-30 17:11 UTC
Last version of Memtest86+ is 7.00. Could you update Memtest86+ in GRUB menu?

https://www.memtest.org

**Comment by Fantu** [comment] 2024-07-01 08:14
Ubuntu 24.04 (base of the mint 22) have already 7.00: https://packages.ubuntu.com/noble/memtest86+

**Comment by Ensam57** [comment] 2024-07-01 10:21
@Fantu The problem is not in the packages but in the GRUB menu of the LM DVD iso.

**Comment by InfoLibre** [comment] 2024-07-01 16:19
![image](https://github.com/linuxmint/mint22-beta/assets/3955499/00e8bbda-353c-43f5-a8fe-3b2887caa44b)

**Comment by InfoLibre** [comment] 2024-07-01 16:20
![image](https://github.com/linuxmint/mint22-beta/assets/3955499/16561fda-bcf5-4cce-95b0-86ba520042e0)

**Comment by Fantu** [comment] 2024-07-01 17:22
So I suppose that installer image is not updated, 7.00 was synced from Debian months ago, before the 24.04 release freeze

**Comment by InfoLibre** [comment] 2024-07-01 17:33
Yes, the installer image is not updated.

**Comment by clefebvre** [comment] 2024-07-06 11:46
Fixed in next ISO.

**Closed by clefebvre** 2024-07-06 11:46 UTC

**Comment by InfoLibre** [comment] 2024-07-06 11:55
Thank you very much :+1:
