### ISSUE TITLE
Apps did not show up after git clone build installation (Mainly from Dolphin Emulator Global Build).

### ISSUE THREAD

**Issue by ThePizzaler** [linuxmint/mint22-beta#40] opened 2024-07-01 21:49 UTC
Because it did show up from other desktop environments (Cosmic, KDE, and Gnome. I could miss more) this means that Cinnamon itself didn't.

**Comment by clefebvre** [comment] 2024-07-04 19:17
I'm sorry I don't understand what we're talking about here... what are you building? what apps?

**Comment by ThePizzaler** [comment] 2024-07-05 16:20
I'm sorry for the late reply

What I meant is that I was building the Dolphin Emulator (GC-WII) using the steps correctly. https://github.com/dolphin-emu/dolphin/wiki/Building-for-Linux Since the flatpak of dolphin emulator is not official.

And it did succeed, but somehow when I search it from the start menu, I can't find it. Meaning it well be a pain in a butt to how to find and open dolphin emulator manually from file manager.

**Comment by clefebvre** [comment] 2024-07-17 11:02
Make sure it provides a /usr/share/applications .desktop file, that's how it usually gets into the app menu.

Anyway, I'm closing this since it's not a bug related to this BETA.

**Closed as completed by clefebvre** 2024-07-17 11:02 UTC
Labels: observation
