### ISSUE TITLE
Account Details Fails To Open After User Picture Is Selected in Users and Groups

### ISSUE THREAD

**Issue by Harry-W-Haines-III** [linuxmint/mint22-beta#116] opened 2024-07-07 20:08 UTC
How to reproduce:

1. Do a an install to a hard drive and update everything (making sure all the latest changes are applied).

2. Go to System Settings.
3. Go to Users and Groups.
4. Click on the current account (notice while doing this, there a small segfault going on in the background).

Right after [COMMAND=/usr/share/cinnamon/cinnamon-settings-users/cinnamon-settings-users.py] in the syslog but not logged in System Reports | Crash Reports.
Jul 07 15:56:15 powerbar systemd-coredump[4875]: [🡕] Process 4873 (w) of user 0 dumped core.
                                                 
                                                 Module libzstd.so.1 from deb libzstd-1.5.5+dfsg2-2build1.amd64
                                                 Module libsystemd.so.0 from deb systemd-255.4-1ubuntu8.1.amd64
                                                 Stack trace of thread 4873:
                                                 #0  0x000059d4a2f58e73 n/a (w + 0x2e73)
                                                 #1  0x000059d4a2f59161 n/a (w + 0x3161)
                                                 #2  0x000059d4a2f5a0e0 n/a (w + 0x40e0)
                                                 #3  0x000059d4a2f58a8f n/a (w + 0x2a8f)
                                                 #4  0x000075856542a1ca __libc_start_call_main (libc.so.6 + 0x2a1ca)
                                                 #5  0x000075856542a28b __libc_start_main_impl (libc.so.6 + 0x2a28b)
                                                 #6  0x000059d4a2f58d25 n/a (w + 0x2d25)
                                                 ELF object binary architecture: AMD x86-64

5. Change the account picture to something else from the black & white default.
6. In this case used chess pieces.
7. Close the window.

8. In a terminal window type "cinnamon-settings user"
9. Observe the Python error messages.

Using PAM module (python3-pam)
/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py:458: DeprecationWarning: Gtk.Window.set_wmclass is deprecated
  self.window.set_wmclass(wm_class, wm_class)
Loading User module
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 811, in <module>
    window = MainWindow()
             ^^^^^^^^^^^^
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 330, in __init__
    if self.load_sidepage_as_standalone():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 464, in load_sidepage_as_standalone
    self.go_to_sidepage(sp_data.sp, user_action=False)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 185, in go_to_sidepage
    sidePage.build()
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 212, in build
    self.module.on_module_selected()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_user.py", line 56, in on_module_selected
    self.face_button = PictureChooserButton(num_cols=4, button_picture_width=64, menu_picture_width=64*self.scale, keep_square=True)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: PictureChooserButton.__init__() got an unexpected keyword argument 'button_picture_width'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 228, in partial_apport_excepthook
    return apport_excepthook(binary, exc_type, exc_obj, exc_tb)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 144, in apport_excepthook
    os.open(pr_filename, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), "wb"
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/var/crash/_usr_share_cinnamon_cinnamon-settings_cinnamon-settings.py.1000.crash'

--
Could this be caused by something as simple as an apparmor issue?

**Comment by WhosyVox** [comment] 2024-07-08 06:39
My packages aren't fully updated. As of right now I do get a pause in step 4. But no crash when opening an user/account settings.

Looking at the cause of the pause, it appears to be caused by the `w` application (as your own log message suggested). The application calls `w -sh $USER`. It appears that `w -s` results now in a SIGSEGV.

This seems to be a known problem on the Ubuntu 24.04 base.

https://bugs.launchpad.net/ubuntu/+source/procps/+bug/2067250
https://gitlab.com/procps-ng/procps/-/issues/301

Having now updated my Mint22-Cinnamon system to the latest packages, repeating steps 1 through 8 does indeed cause the crash and errors you mentioned previously. So this issue is likely related to a recent update.

(I have a snapshot and can fetch my before/after package versions if and when requested.)

**Comment by mtwebster** [comment] 2024-07-08 13:34
Fixed by 86c071cde5ec8325f278ae4341810c969d4eb88e

**Closed as completed by mtwebster** 2024-07-08 13:34 UTC

**Comment by Harry-W-Haines-III** [comment] 2024-07-08 13:39
What was 86c071cde5ec8325f278ae4341810c969d4eb88e?

**Comment by fredcw** [comment] 2024-07-08 13:55
https://github.com/linuxmint/cinnamon/commit/86c071cde5ec8325f278ae4341810c969d4eb88e

**Comment by mtwebster** [comment] 2024-07-08 14:08
Sorry, forgot this wasn't the cinnamon repo.

**Comment by Harry-W-Haines-III** [comment] 2024-07-08 14:09
Thanks!
