### ISSUE TITLE
My giant list of bugs and regressions.

### ISSUE THREAD

**Issue by crhy** [linuxmint/mint22-beta#91] opened 2024-07-05 05:43 UTC
1) Grub is ugly.  Ugly font, lettering too small on a generic 1080p monitor
2) WAY too long to boot off of USB key.  Likely a systemD issue.
3) Cannot save a file to the home folder from the live USB environment.
4) Hideous default theme choice in MATE.
5) LOTS of broken Compiz Config issues.  I’ve reported on this for the last 10+ versions of Mint.
	a) No zoom out on cube rotate
	b) rotate left and right shortcuts not the defaults
	c) rotate with active window shortcuts also not the defaults
	d) Screenshot key not the default PrtScrn key
	e) 3d windows not on by default
	f) rotate cube speed settings are too slow
	g) transparent cube during rotate
	h) transparent cube caps should be default
	I) 
6) Software Manager just shows “Generating Cache” for much too long on initial boot.  No progress bar.
7) Flatpaks are completely broken.  I tried several ways of installing, command line, software manager… NOTHING worked.  This is a major regression from 21.3.
8) No GIMP by default.
9) Software Manager featured projects are incredibly stupid.
10) htop not installed by defaultt.
11) neofetch has that annoying issue where you have to scroll up one line for it to look right.
12) Default Terminal Window theme ugly.
13) Could not import OBS profile/settings
14) Nvidia drivers do not work in the live USB environment, no NVENC codecs.
15) OBS codec defaults not selected in a way that is usable out of the box.
16) New Matrix client is useless, requires an ID, email, nazi garbage, no anonymous usage possible.
17) Wallpaper menu takes way too long load.
18) Software Manager missing most of the most popular games and a lot of the most popular apps.
19) Terrible Default app selection in the start menu
	a) Libre Office Write missing
	b) Gimp missing
	c) OBS-studio missing
	d) Audacious missing
	e) Chromium browser missing
	f) Aisleriot missing
20) I’ve submitted many MANY bug reports in the past, and they were ignored before the release.

PLEASE PLEASE PLEEEEEAAAASE don’t do this that time.

Here's the detail in video format:
https://rumble.com/v55mu8v-unbelievably-frustrating-and-buggy-mint-22-beta-test.html

Also note, I could not post this list on the blog, I had to break it into several messages, and then it never let me post 12-20 at all no matter what I did.  So your blog is also broken.

**Comment by clefebvre** [comment] 2024-07-05 07:45
You did well to post your issue here and not on the blog. This is where we focus for bug reports.

However,

> Be precise in your issue and follow the template as much as possible. We know it takes time to report issues and to troubleshoot, but the quality of the feedback makes all the difference. When the issue is clearly analyzed and it touches an area we're empowered to fix, we're able to fix it much faster.
> 
> Please be aware that a vast majority of reported issues do not get fixed because:
> 
>     We don't understand their cause (observations describe a behaviour but not the cause of that behaviour)
>     They're not reproducible
>     They affect components which are upstream from us (proprietary drivers, or components which are maintained by Debian/Ubuntu)
>     They're beyond the scope
>     They've already been analyzed and it didn't lead to a fix
> 
> What we look for the most during the BETA phase are regressions coming from us. If an issue is new, and it's specific to this release, and it's about a component we develop, then we should be able to fix rapidly and that's our primary target during the BETA phase.

There's no need to:

- ignore https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/
- report duplicates
- report observations
- report things that were already closed or marked as wontfix in the past
- give subjective opinions about decisions that were already made

**Comment by clefebvre** [comment] 2024-07-05 07:55
1) subjective, observation
2) subjective, observation
3) not part of the scope
4) subjective, not explained
5) already closed in the past
6) by design, subjective
7) interesting but not enough details
8) by design, wontfix
9) subjective and not enough details
10) not supposed to be
11) not enough details
12) subjective
13) no details
14) not possible (assuming I get this right, not a lot of details)
15) no idea what you're talking about
16) that's also a plus
17) wallpaper menu??
18) probably not, no.
19) subjective
20) if interesting feedback like the one in 7 was buried in a long list of duplicates or subjective points and not detailed like it's the case here, that's probably why.

This is my quick feedback on your very long list of vague, non-detailed points. Do not waste your own time and ours by reporting things you know we won't change, or things you already reported in the past. We read it all. If you did before, you don't need to do it again, especially if we already answered. Spend time instead in detailing new feedback, on actual bugs, not subjective taste, and give each bug its own dedicated report.

I have a feeling your Flatpak issue has to do with apparmor, which is already reported... but how can I know, since you gave no details at all.

**Closed as completed by clefebvre** 2024-07-05 07:55 UTC

**Comment by crhy** [comment] 2024-07-05 09:04
So you didn't watch the video where I went into great detail? Honestly, I
don't know what to tell you. I'm very disappointed in your response.

My video goes into great detail on every single aspect of every single
thing that I reported. You closed the issue without fixing it. As I
expected because that's what you've done in the past.

I will now replace you.

**Comment by clefebvre** [comment] 2024-07-05 09:34
I just spent 2 hours giving you feedback about it on Matrix, where you linked this and your video.

**Comment by crhy** [comment] 2024-07-05 14:07
This took you two hours?!?!

_subjective, observation
subjective, observation
not part of the scope
subjective, not explained
already closed in the past
by design, subjective
interesting but not enough details
by design, wontfix
subjective and not enough details
not supposed to be
not enough details
subjective
no details
not possible (assuming I get this right, not a lot of details)
no idea what you're talking about
that's also a plus
wallpaper menu??
probably not, no.
subjective
if interesting feedback like the one in 7 was buried in a long list of duplicates or subjective points and not detailed like it's the case here, that's probably why.
This is my quick feedback on your very long list of vague, non-detailed points. Do not waste your own time and ours by reporting things you know we won't change, or things you already reported in the past. We read it all. If you did before, you don't need to do it again, especially if we already answered. Spend time instead in detailing new feedback, on actual bugs, not subjective taste, and give each bug its own dedicated report.

I have a feeling your Flatpak issue has to do with apparmor, which is already reported... but how can I know, since you gave no details at all._

You must type less than 5 wpm.  No wonder you don't want to fix the bugs.

Here's my new follow up video.  It's spicier.  I've been trying to get you guys to fix Compiz for over a decade now.  It's better in the last two releases but still has lots of problems.  And it would be such an easy fix.  Should I screen cap just the settings that need fixed individually?

https://old.bitchute.com/video/D5iEmJ5uTqa5/

**Comment by clefebvre** [comment] 2024-07-05 15:33
You were borderline on Matrix already when talking about Ireland having some "ridiculous French currency" or implying you needed to speak Arabic. I told you: Don't go too low or I won't be able to continue to interact with you. And now I'm paid by the CIA? You're funny but we're done here.

Thanks for the entertaining videos and some valuable feedback on favs in the app menu and software manager.

PS: No need for a screen cap of the compiz settings. You already showed them to me in the past, I already told you I didn't want to do them.
