### ISSUE TITLE
Phantom "NVIDIA Prime" display showing up and acting like a second monitor

### ISSUE THREAD

**Issue by canofjuice** [linuxmint/mint22-beta#171] opened 2024-07-12 21:30 UTC
![Screenshot from 2024-07-12 23-27-53](https://github.com/user-attachments/assets/8ebe85a3-fc31-402e-b66e-3922f0f12db7)

Both Cinnamon Display settings and NVIDIA X Settings show a phantom 1024x768 display. NVIDIA settings calls it "PRIME Display" and acts as if it's enabled and the cursor can go in it.

Apologies for the theme flashbang.

**Comment by Harry-W-Haines-III** [comment] 2024-07-12 22:14
This is a duplicate of #31

**Closed as completed** 2024-07-18 16:34 UTC
Labels: duplicate
