### ISSUE TITLE
cinnamon: Using the menu doesn't stop fullscreen mode

### ISSUE THREAD

**Issue by Iaokhan** [linuxmint/mint22-beta#65] opened 2024-07-03 08:31 UTC
Under cinnamon, the game return on the desktop does not work. The desktop is displayed but as soon as you click on a link, you immediately return to the game (full screen)

**Comment by clefebvre** [comment] 2024-07-04 09:10
What game ??

**Comment by Iaokhan** [comment] 2024-07-04 09:37
All games in full screen under Steam

**Comment by fredcw** [comment] 2024-07-04 10:22
@Iaokhan What do you do to show the desktop and what are you clicking on exactly that returns you to the game? Normally, when something is running in full screen, the desktop is not available unless you minimise the full screen app.

**Comment by Iaokhan** [comment] 2024-07-04 11:33
![Capture d’écran du 2024-07-04 13-30-11](https://github.com/linuxmint/mint22-beta/assets/174593698/dae96bc2-3c4f-468f-a077-5ba8c48f2a23)

Precision, this happens when using the super key and a mouse click. I don't have the problem with alt+tab

**Comment by clefebvre** [comment] 2024-07-04 14:40
This doesn't sound like a bug to me, you're still in fullscreen mode with the game focused. Mapped windows aren't supposed to break that focus.

When you alt-tab you unfocus the game, that's a different story.

**Comment by fredcw** [comment] 2024-07-05 04:31
Pressing the Super key while focus is on a fullscreen app, opens the menu applet which also shows the panel as a side effect. The problem is that when you click anywhere outside the menu applet (including on the panel), the menu applet closes and the panel disappears along with the menu. This isn't really a bug as such but it is counterintuitive because if the panel is visible, the user may expect it to be usable.

There's a cinnamon issue for this: https://github.com/linuxmint/cinnamon/issues/11658

I don't really know what the solution to this is or if it's possible to have a usable panel shown on top of a fullscreen app.

**Comment by clefebvre** [comment] 2024-07-05 11:40
We could inhibit Super key shortcut or not respond to it while in fullscreen... ?

**Comment by clefebvre** [comment] 2024-07-05 11:41
What's the exact use case here? The game shows a link to a web page.. you click on it.. it maps a new browser window but you don't see it? Why is the Super Key pressed and the menu needed?

**Comment by fredcw** [comment] 2024-07-05 13:33
The use case is that you're playing a fullscreen game and you need to quickly access the panel for some reason, change volume, check time, open system settings, etc. Actually, now that you ask the question, the solution is obvious - set a keyboard shortcut to minimise window. I guess people press the super key, see the panel and would like it to be usable, or maybe they'd like the game to be visible in the background while they use the panel? In any case, just setting a minimise window shortcut (Alt-F3 say) seems just as good but I never thought of that before for some reason, I've always just used alt-tab instead.

**Comment by Iaokhan** [comment] 2024-07-06 07:59
It's exactly that. We may need to see a solution for a game, retrieve a code or simply need to make a setting. I have always used this method to launch another application, alt-tab not being a reflex because it implies already having another program open. Having a menu that appears but is not usable is frustrating

**Comment by fredcw** [comment] 2024-07-06 22:59
Instead of pressing super key to show menu or using alt-tab, there are other options:

* super-d to show desktop
* alt-space followed by n to minimise window/game
* Set a keyboard shortcut to minimise window in keyboard settings

**Comment by fredcw** [comment] 2024-07-06 23:51
>We could inhibit Super key shortcut or not respond to it while in fullscreen... ?

Yes, I think that's probably the best solution. Other solutions would be to either never show the panel if it isn't usable simply because of how counterintuitive it is or make the panel usable even in fullscreen. These would be more complicated to implement though and I don't know enough about the relevant code atm to do it. I tried removing the `this.panel.peekPanel()` call from the menu applet but it doesn't make a difference in fullscreen.

**Comment by JosephMcc** [comment] 2024-07-07 03:12
> Other solutions would be to either never show the panel if it isn't usable simply because of how counterintuitive it is or make the panel usable even in fullscreen

I'm pretty sure this is exactly how it used to work. Users complained because the menu would show up sort of floating since the panel wasn't there. So it was changed to what it is now. Now that's being complained about. Probably just need to pick a solution and stick with it. Quit changing it back and forth.

**Comment by pilatomic** [comment] 2024-07-07 22:11
As a tip, my preferred way to do anything while running a full screen app / game is to simply switch to another workspace (Ctrl + Alt + Left / Right Arrow).

**Comment by fredcw** [comment] 2024-07-08 07:08
@JosephMcc You're probably right, best to just remind people of the other options then that they're probably unaware of if they report the "bug".

**Comment by Iaokhan** [comment] 2024-07-09 08:53
Any desktop works like this. If the menu appears, you can click on an application to launch it without further manipulation. I'm just wondering about the point of showing an unusable menu with this key.

**Comment by Harry-W-Haines-III** [comment] 2024-07-09 12:55
The solution is to buy a gaming keyboard that allows the user to inhibit the super key.  Personally for every day use, I would always want the super key to bring up the menu no matter what mode the screen is in.  I'm in agreement with @JosephMcc not to keep changing it.

**Comment by Qronikarz** [comment] 2024-07-10 17:09
Maybe something related. In older Mint when I had only one game open and wanted to open Firefox to search for something nothing was clickable at all, but currently I can open the menu with Windows key button and open firefox so it's nice. However the panel doesn't work and it also sometimes disappears:
![panel](https://github.com/linuxmint/mint22-beta/assets/84787215/a770ffb0-023f-4164-973f-70993c5783b5)
![nopanel](https://github.com/linuxmint/mint22-beta/assets/84787215/8cb35178-ac1b-472c-96db-dc0321346aec)
Another thing maybe worth noting is the fact that it runs on "exclusive fullscreen" and after you open something from mint menu the game automatically sets the mode to windowed.
I have fullscreen compositions disabled in Mint settings

**Comment by clefebvre** [comment] 2024-07-11 14:58
> > Other solutions would be to either never show the panel if it isn't usable simply because of how counterintuitive it is or make the panel usable even in fullscreen
> 
> I'm pretty sure this is exactly how it used to work. Users complained because the menu would show up sort of floating since the panel wasn't there. So it was changed to what it is now. Now that's being complained about. Probably just need to pick a solution and stick with it. Quit changing it back and forth.

Also, you just said one use case was to check the date/time in the panel, so there is value in showing it.

**Comment by clefebvre** [comment] 2024-07-11 15:01
OK I'll close this since it's not a bug, even less so a BETA bug. We can consider ideas as improvements for the future but outside of the BETA phase.

**Closed as completed by clefebvre** 2024-07-11 15:01 UTC
