### ISSUE TITLE
xed: white line on left side

### ISSUE THREAD

**Issue by Qronikarz** [linuxmint/mint22-beta#5] opened 2024-06-30 12:57 UTC
This is on default settings (the preview on the right doesn't change anything)
![xedline](https://github.com/linuxmint/mint22-beta/assets/84787215/67c254cb-5906-4167-94f4-486ce4a17ecf)
I think it's because of the line numbers, because that's the same color when you enable line numbering in the preferences:
![xedlinenumbers](https://github.com/linuxmint/mint22-beta/assets/84787215/354cc6d2-37f8-4fcc-b295-9b7a44745081)

**Comment by JosephMcc** [comment] 2024-07-01 20:10
A few tests show I should be able to fix this in the theme. I'll see if I can get a fix done for it.

**Comment by clefebvre** [comment] 2024-07-04 15:43
I had a look at that... 

Tango doesn't work well in dark theme (line numbers column is light grey)  but that's a different bug report: https://github.com/linuxmint/mint22-beta/issues/60.

What this report is about is the fact that a line is visible even when the line numbers aren't enabled in the prefs. That's a regression since 21.3.

**Comment by clefebvre** [comment] 2024-07-04 15:53
Actually... I take it back. It looks like this was already the case in 21.3.

![image](https://github.com/linuxmint/mint22-beta/assets/1138515/11f3556f-a43c-4500-ad27-4dc7b8ce2482)

It's hard to notice it because the line color matches the theme there (other report), but picking a black line, it's visible.

**Comment by clefebvre** [comment] 2024-07-04 17:04
OK I'm closing this because:

- It's not a regression (it's always been like that)
- It's an upstream issue in gtksourceview, not in Xed.
- It's only noticeable because of #60, which we'll be fixing anyway.

**Closed by clefebvre** 2024-07-04 17:04 UTC
Labels: bug
