### ISSUE TITLE
Not able to restore system to usable state after screens turn off

### ISSUE THREAD

**Issue by User-DMG** [linuxmint/mint22-beta#88] opened 2024-07-04 17:32 UTC
![image](https://github.com/linuxmint/mint22-beta/assets/173769230/3cfec068-4dda-45ca-941c-feb049972eb0)

My pc needs to be hard restarted every single time the monitors turn off. It also happens every time my pc goes to sleep too.

My PC consists of amd 5700x cpu, asrock x570 steel legend, 32gb of ram and 7900xtx gpu. Using gnome desktop environment allows me to successfully restore the session.

I have not written many bug reports so I hope this is enough information.

https://github.com/linuxmint/mint22-beta/assets/173769230/0c921180-9408-4bcd-99d9-74c818b3dd58

**Comment by User-DMG** [comment] 2024-07-04 18:39
As an aditional that might be somewhat helpful is that I have found out that Gnome desktop environment is able to fully wake up successfully on this pc.

**Comment by clefebvre** [comment] 2024-07-04 19:33
Does it happen with MATE/Xfce?

**Comment by User-DMG** [comment] 2024-07-04 19:36
Yes, I have tried both mate and xfce and experience the same issue.

**Comment by clefebvre** [comment] 2024-07-04 20:27
When you say GNOME, you mean Ubuntu 24.04? or you installed GNOME on Mint 22?

**Comment by User-DMG** [comment] 2024-07-04 20:33
I mean the brand new ubuntu and other distributions with gnome desktop environment. I can try it out for you in a bit by installing gnome desktop environment in linux mint 22.

**Comment by User-DMG** [comment] 2024-07-04 20:52
Hi!
I ran the same test and it seems to function as inteded after simply running sudo apt install gnome choosing gdm and rebooting the pc and logging into gnome session.

**Comment by clefebvre** [comment] 2024-07-05 11:38
OK, it could be related to Xorg or lightdm then. Can you check in dmesg, in .xsession-errors and in the system logs for clues after a crash happens?

**Comment by User-DMG** [comment] 2024-07-05 12:15
[xsession-errors.txt](https://github.com/user-attachments/files/16109518/xsession-errors.txt)
![Screenshot from 2024-07-05 15-14-46](https://github.com/linuxmint/mint22-beta/assets/173769230/95b9c5eb-4f3b-4848-8e23-d144914813a5)


I believe this is the data you are asking for.

**Comment by clefebvre** [comment] 2024-07-06 19:10
Hi, I'm sorry, I don't see any probably cause. I'll close this issue since we can't find the root cause. Don't hesitate to request a reopen if you find a bug and identify the cause of the issue.

**Closed as completed by clefebvre** 2024-07-06 19:10 UTC
Labels: observation
