### ISSUE TITLE
Issues with certain AppImages not working at all (Yes, I have enabled permissions)

### ISSUE THREAD

**Issue by Blmyers85** [linuxmint/mint22-beta#155] opened 2024-07-10 20:18 UTC
<img width="489" alt="error" src="https://github.com/linuxmint/mint22-beta/assets/90371658/8dd75c7e-dae4-494e-b4a9-5a104f417486">

I'm just gonna have to fresh install again some time.  Been having all sorts of issues.  Sound cutouts, half my appimages will not even start up, random crashes.

**Comment by DigitalArchon** [comment] 2024-07-11 14:12
This I believe is directly related to issue: https://github.com/linuxmint/mint22-beta/issues/82

If you run it with --no-sandbox it will work for now.

**Comment by clefebvre** [comment] 2024-07-11 14:25
^^ Yes, that definitely looks like a duplicate of linuxmint/mint22-beta#82.

**Closed as completed by clefebvre** 2024-07-11 14:25 UTC
