### ISSUE TITLE
Nemo: Action layout - items are not translated

### ISSUE THREAD

**Issue by Angedestenebres** [linuxmint/mint22-beta#204] opened 2024-07-20 07:38 UTC
Related to: https://github.com/linuxmint/mint22-beta/issues/58

A fix has been done and the translation is better but actions are not not translated yet, see screen:

![VirtualBox_Linux Mint 22_20_07_2024_09_35_03](https://github.com/user-attachments/assets/0f9de477-013c-4c6a-ad6f-e22eb86d5b89)

**Comment by clefebvre** [comment] 2024-07-20 08:42
I think this was by design since you can override the label in here.. but I agree, the default label shouldn't be the default untranslated label, it should be the one that shows up in the context menus, i.e. the translated one.

**Comment by clefebvre** [comment] 2024-07-20 08:56
Fixed in nemo 6.2.5

**Closed as completed** 2024-07-20 08:56 UTC
Labels: bug
