### ISSUE TITLE
Crash and error when adding multimedia codecs

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/mint22-beta#25] opened 2024-06-30 20:38 UTC
I did not check the box to install multimedia codecs at the beginning of LM Cinnamon installation.
After LM installation, I made the updates and after, installed the multimedia codecs. The session crashed and then, impossible to open a new session (casper error or something like that). I rebooted and tried again  to install the multimedia codecs. There's this error:

![image](https://github.com/linuxmint/mint22-beta/assets/3955499/0c56aa52-1414-4902-95c7-51d24d5d0dd6)

I closed this Window and then, the installation window remained grey, like that:

![image](https://github.com/linuxmint/mint22-beta/assets/3955499/19d71757-14ee-498e-95ac-235d50eb8db2)

Impossible to close it with a click on the cross at the corner. I had to close it with a right click+menu close, on its icon in the task bar.

**Comment by Fantu** [comment] 2024-07-01 08:33
I didn't find from a fast look on some mint* repositories where is the function of codec install, but I suppose it don't use the metapackage for libavcodec-extra
I think is better to use the meta package (libavcodec-extra) that link to the latest/correct version, in ubuntu 24.04 version is libavcodec-extra60, so it doesn't have to be updated between mint versions.

**Comment by clefebvre** [comment] 2024-07-01 15:13
Duplicate of https://github.com/linuxmint/mint22-beta/issues/10.

**Closed by clefebvre** 2024-07-01 15:13 UTC
