### ISSUE TITLE
I don't have audio on my laptop

### ISSUE THREAD

**Issue by Angelca6** [linuxmint/mint22-beta#50] opened 2024-07-02 05:34 UTC
I installed Linux Mint 22 on my Honor magicbook 15 laptop to test and I don’t have audio, with Linux Mint 21.3 the audio works. This laptop has the Realtek ALC256 chip.

**Comment by Angelca6** [comment] 2024-07-02 06:02
The problem started from linux Mint 21.1

**Comment by adrianlopezgalera** [comment] 2024-07-02 13:30
Almost everything related to devices is not system dependent. It's probably due to the kernel version. Have you modified the version that comes with Mint 21.3? Is this the Edge version?

If it is a new device, you can probably fix it by updating the kernel that comes with Mint 22.

Regards.

**Comment by LinuxOnTheDesktop** [comment] 2024-07-03 01:53
> It's probably due to the kernel version.

Well, Mint 22 does swap in PipeWire instead of PulseAudio . .

**Comment by adrianlopezgalera** [comment] 2024-07-03 11:08
> > It's probably due to the kernel version.
> 
> Well, Mint 22 does swap in PipeWire instead of PulseAudio . .

A coincidence does not equal a correlation. In any case, we need more data to help. It is impossible to determine the disease through a single symptom. :)

Regards.

**Comment by clefebvre** [comment] 2024-07-04 09:23
The root cause needs to be found. Use the forums/chat to seek help and troubleshoot this issue. Try to find exactly what's going on. Is is the kernel, is it pipewire, etc..

**Comment by Angelca6** [comment] 2024-07-04 14:29
Dear Clem, I am trying Linux Mint 22 in live mode and the laptop does not make any sound. I have tried YouTube, music files, and videos and nothing works. In Linux Mint cinnamon 21.3 all sounds work correctly whether using the distribution in live or installed mode. I share the information about my system.
System:
  Kernel: 6.8.0-35-generic arch: x86_64 bits: 64 compiler: gcc v: 13.2.0 clocksource: tsc
  Desktop: Cinnamon v: 6.2.2 tk: GTK v: 3.24.41 wm: Muffin v: 6.2.0 vt: 7 dm: LightDM v: 1.30.0
    Distro: Linux Mint 22 Wilma base: Ubuntu 22.04 jammy
Machine:
  Type: Laptop System: HONOR product: BBR-WAX9 v: M1010 serial: <superuser required>
  Mobo: HONOR model: BBR-WAX9-PCB v: M1010 serial: <superuser required> part-nu: C170
    uuid: <superuser required> UEFI: HONOR v: 3.15 date: 02/22/2022
Battery:
  ID-1: BAT1 charge: 32.3 Wh (83.5%) condition: 38.7/41.6 Wh (93.1%) volts: 12.2 min: 11.5
    model: Desay HB4792J5ECW-31 type: Li-ion serial: <filter> status: discharging cycles: 105
CPU:
  Info: dual core model: Intel Core i3-10110U bits: 64 type: MT MCP smt: enabled
    arch: Comet/Whiskey Lake note: check rev: C cache: L1: 128 KiB L2: 512 KiB L3: 4 MiB
  Speed (MHz): avg: 3852 high: 4005 min/max: 400/4100 cores: 1: 4005 2: 3701 3: 4005 4: 3700
    bogomips: 20799
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: Intel CometLake-U GT2 [UHD Graphics] vendor: QUANTA driver: i915 v: kernel
    arch: Gen-9.5 ports: active: eDP-1 empty: DP-1,HDMI-A-1 bus-ID: 00:02.0 chip-ID: 8086:9b41
    class-ID: 0300
  Device-2: IMC Networks HD Camera driver: uvcvideo type: USB rev: 2.0 speed: 480 Mb/s lanes: 1
    bus-ID: 1-6:3 chip-ID: 13d3:5480 class-ID: fe01 serial: <filter>
  Display: x11 server: X.Org v: 21.1.11 with: Xwayland v: 23.2.6 driver: X: loaded: modesetting
    unloaded: fbdev,vesa dri: iris gpu: i915 display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1920x1080 s-dpi: 96 s-size: 508x285mm (20.00x11.22") s-diag: 582mm (22.93")
  Monitor-1: eDP-1 model: BOE Display 0x0872 res: 1920x1080 hz: 60 dpi: 142
    size: 344x194mm (13.54x7.64") diag: 395mm (15.5") modes: 1920x1080
  API: EGL v: 1.5 hw: drv: intel iris platforms: device: 0 drv: iris device: 1 drv: swrast
    surfaceless: drv: iris x11: drv: iris inactive: gbm,wayland
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: intel mesa v: 24.0.5-1ubuntu1 glx-v: 1.4
    direct-render: yes renderer: Mesa Intel UHD Graphics (CML GT2) device-ID: 8086:9b41
Audio:
  Device-1: Intel Comet Lake PCH-LP cAVS vendor: QUANTA driver: sof-audio-pci-intel-cnl
    bus-ID: 00:1f.3 chip-ID: 8086:02c8 class-ID: 0403
  API: ALSA v: k6.8.0-35-generic status: kernel-api
  Server-1: PipeWire v: 1.0.5 status: active with: 1: pipewire-pulse status: active
    2: wireplumber status: active 3: pipewire-alsa type: plugin
Network:
  Device-1: Intel Comet Lake PCH-LP CNVi WiFi driver: iwlwifi v: kernel bus-ID: 00:14.3
    chip-ID: 8086:02f0 class-ID: 0280
  IF: wlp0s20f3 state: up mac: <filter>
Bluetooth:
  Device-1: Intel Bluetooth 9460/9560 Jefferson Peak (JfP) driver: btusb v: 0.8 type: USB rev: 2.0
    speed: 12 Mb/s lanes: 1 bus-ID: 1-10:4 chip-ID: 8087:0aaa class-ID: e001
  Report: hciconfig ID: hci0 rfk-id: 0 state: up address: <filter> bt-v: 5.1 lmp-v: 10
    sub-v: 20f9 hci-v: 10 rev: 20f9 class-ID: 7c010c
Drives:
  Local Storage: total: 494.58 GiB used: 3.9 MiB (0.0%)
  ID-1: /dev/nvme0n1 vendor: Kingston model: SNV2S500G size: 465.76 GiB speed: 63.2 Gb/s lanes: 4
    tech: SSD serial: <filter> fw-rev: ELFKAN.2 temp: 32.9 C scheme: GPT
  ID-2: /dev/sda vendor: Kingston model: DataTraveler 3.0 size: 28.82 GiB type: USB rev: 3.2
    spd: 5 Gb/s lanes: 1 tech: N/A serial: <filter> scheme: MBR
Partition:
  ID-1: / size: 3.75 GiB used: 25 MiB (0.7%) fs: overlay source: ERR-102
  ID-2: /var/log size: 25.55 GiB used: 3.9 MiB (0.0%) fs: ext4 dev: /dev/sda3
Swap:
  Alert: No swap data was found.
USB:
  Hub-1: 1-0:1 info: hi-speed hub with single TT ports: 12 rev: 2.0 speed: 480 Mb/s lanes: 1
    chip-ID: 1d6b:0002 class-ID: 0900
  Device-1: 1-5:2 info: Logitech M185 compact wireless mouse type: mouse
    driver: hid-generic,usbhid interfaces: 1 rev: 1.1 speed: 12 Mb/s lanes: 1 power: 50mA
    chip-ID: 046d:c542 class-ID: 0301
  Device-2: 1-6:3 info: IMC Networks HD Camera type: video driver: uvcvideo interfaces: 3
    rev: 2.0 speed: 480 Mb/s lanes: 1 power: 500mA chip-ID: 13d3:5480 class-ID: fe01 serial: <filter>
  Device-3: 1-10:4 info: Intel Bluetooth 9460/9560 Jefferson Peak (JfP) type: bluetooth
    driver: btusb interfaces: 2 rev: 2.0 speed: 12 Mb/s lanes: 1 power: 100mA chip-ID: 8087:0aaa
    class-ID: e001
  Hub-2: 2-0:1 info: super-speed hub ports: 6 rev: 3.1 speed: 10 Gb/s lanes: 1 chip-ID: 1d6b:0003
    class-ID: 0900
  Device-1: 2-3:2 info: Kingston DataTraveler 100 G3/G4/SE9 G2/50 Kyson type: mass storage
    driver: usb-storage interfaces: 1 rev: 3.2 speed: 5 Gb/s lanes: 1 power: 296mA chip-ID: 0951:1666
    class-ID: 0806 serial: <filter>
Sensors:
  System Temperatures: cpu: 72.0 C pch: 39.0 C mobo: N/A
  Fan Speeds (rpm): N/A
Repos:
  Packages: pm: dpkg pkgs: 1992
  Active apt repos in: /etc/apt/sources.list
    1: deb cdrom:[Linux Mint 22 _Wilma_ - Release amd64 20240625]/ noble contrib main
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb http: //packages.linuxmint.com wilma main upstream import backport
    2: deb http: //archive.ubuntu.com/ubuntu noble main restricted universe multiverse
    3: deb http: //archive.ubuntu.com/ubuntu noble-updates main restricted universe multiverse
    4: deb http: //archive.ubuntu.com/ubuntu noble-backports main restricted universe multiverse
    5: deb http: //security.ubuntu.com/ubuntu/ noble-security main restricted universe multiverse
Info:
  Memory: total: 8 GiB note: est. available: 7.5 GiB used: 1.3 GiB (17.3%)
  Processes: 236 Power: uptime: 3m states: freeze,mem,disk suspend: deep wakeups: 0
    hibernate: platform Init: systemd v: 255 target: graphical (5) default: graphical
  Compilers: gcc: 13.2.0 Client: Unknown python3.12 client inxi: 3.3.34

**Comment by Angelca6** [comment] 2024-07-04 14:33
I get that I need to install a multimedia codec but when I try to do it I get that it can't be installed.
![multimedia codec](https://github.com/linuxmint/mint22-beta/assets/174410992/640a83f5-ba1f-4537-aec3-6bb586e63b15)

![Codecs](https://github.com/linuxmint/mint22-beta/assets/174410992/2365c6c5-b172-415e-9a33-f6840148495f)

**Comment by Angelca6** [comment] 2024-07-04 14:41
I compare some screenshots of my system.
![Screenshot from 2024-07-04 14-09-58](https://github.com/linuxmint/mint22-beta/assets/174410992/6e87f5e3-4848-4f27-96e3-8420d1d70fba)
![Screenshot from 2024-07-04 14-10-19](https://github.com/linuxmint/mint22-beta/assets/174410992/28ff307f-6839-4fd7-b385-16bb1248a8fc)
![Screenshot from 2024-07-04 14-10-51](https://github.com/linuxmint/mint22-beta/assets/174410992/bbe9a854-6b5b-4955-b8ba-689258ec9653)
![Screenshot from 2024-07-04 14-11-03](https://github.com/linuxmint/mint22-beta/assets/174410992/190c15ad-ad98-4e18-a96e-5c0692d799bb)
![Screenshot from 2024-07-04 14-11-16](https://github.com/linuxmint/mint22-beta/assets/174410992/41e9d067-065c-4592-9d08-91f7f8cfcb3d)
![Screenshot from 2024-07-04 14-15-26](https://github.com/linuxmint/mint22-beta/assets/174410992/e4abd3ee-dad2-44d3-a7dd-789c1bdca579)
![Screenshot from 2024-07-04 14-18-24](https://github.com/linuxmint/mint22-beta/assets/174410992/92d705f5-8449-4d1f-a6ed-1beaf0c18c73)
![volumen](https://github.com/linuxmint/mint22-beta/assets/174410992/768464d1-dc3b-4b09-974b-01c236f0b015)

Is it necessary for me to install the operating system on my laptop or is it enough with the live tests if necessary, I am willing to install it to continue with the tests.

**Comment by Angelca6** [comment] 2024-07-04 15:10
I have also tried in live mode with Linux Mint 22 xfce and I don't have audio either.
I share some images of the system. It also tells me to install the multimedia codec but it couldn't.
![Screenshot_2024-07-04_15-02-24](https://github.com/linuxmint/mint22-beta/assets/174410992/97d631ff-fc49-43ca-9112-6f70e3f1c8a8)
![Screenshot_2024-07-04_15-07-29](https://github.com/linuxmint/mint22-beta/assets/174410992/23910161-9607-4157-877d-39973dc4250c)
![Screenshot_2024-07-04_14-57-29](https://github.com/linuxmint/mint22-beta/assets/174410992/a80be4ed-401a-4cf1-8c2a-2d1bd8c530e5)
![Screenshot_2024-07-04_14-57-47](https://github.com/linuxmint/mint22-beta/assets/174410992/3dc5b0dc-cf02-4c72-9917-97e3e50adbb9)
![Screenshot_2024-07-04_14-58-00](https://github.com/linuxmint/mint22-beta/assets/174410992/28b0f2fc-7bd9-4f8e-ba90-82db0d204ce1)
![Screenshot_2024-07-04_14-58-15](https://github.com/linuxmint/mint22-beta/assets/174410992/db9443e6-c710-453e-89b8-2f8e00faf697)
![Screenshot_2024-07-04_14-58-29](https://github.com/linuxmint/mint22-beta/assets/174410992/911acdec-2753-4a71-9827-7464a23fa7de)
![Screenshot_2024-07-04_15-04-11](https://github.com/linuxmint/mint22-beta/assets/174410992/669e893a-7e45-4fb0-86d7-efc11edac1c8)
![Screenshot_2024-07-04_15-04-23](https://github.com/linuxmint/mint22-beta/assets/174410992/2f0715a6-bb92-4790-b7fc-aa41f1db3429)
![Screenshot_2024-07-04_15-05-11](https://github.com/linuxmint/mint22-beta/assets/174410992/4684fd55-81f8-4e11-98a5-c75586163732)
Thank you very much for your great work with Linux Mint, which is wonderful.

**Comment by clefebvre** [comment] 2024-07-04 19:15
Hi Angel,

I hope you find a solution. A couple of things:

- I can't really help you troubleshoot (I'm too busy sorry) but others might. Don't hesitate to use the forums/chat as well.
- If you find the root cause and it's something we can fix, we'll look into it.
- The codecs can't be installed because of another bug, it's already reported and we're fixing that but...
- ... codecs have no impact on audio here. It's not related.
- It's good that you tested Xfce, this shows it's not a bug in Cinnamon (which is a pulse sound client, so it could have been).
- No need to install the OS, in my opinion it's enough to test in live mode.

My intuition is that this is a kernel issue with your hardware.

**Comment by Angelca6** [comment] 2024-07-05 18:13
Dear Cleam, I thank you very much for your response, I will try changing the Kernel and if it doesn't work, there is no problem because I still have support until 2027 with Linux Mint cinnamon 21.3, after 2027 I will buy an external USB sound card and with that I will be able to continue using linux Mint, which I love.

**Comment by Qronikarz** [comment] 2024-07-06 21:12
While searching for your sound chip it gave one result from Arch forum with PipeWire being at fault.
https://bbs.archlinux.org/viewtopic.php?id=286110
The solution was to install alsa-utils, but Mint 22 already has them installed. Though the Mint 22 doesn't have processes mentioned later (alsa-restore and alsa-state) so maybe that can be a clue.

**Comment by Angelca6** [comment] 2024-07-07 15:27
Thank you very much for the information, greetings

**Comment by clefebvre** [comment] 2024-07-12 09:57
Before spending money, you can install the OS and try to switch back from pipewire to pulseaudio. I'll close the issue as this isn't a bug we can fix, it's all upstream from us.

**Closed as completed by clefebvre** 2024-07-12 09:57 UTC
Labels: observation, upstream
