### ISSUE TITLE
Control Centre Sound Preferences test does not play test audio

### ISSUE THREAD

**Issue by oblongau** [linuxmint/mint22-beta#183] opened 2024-07-17 05:39 UTC
MATE 22 beta, live CD.
Laptop is brand new laptop, LENOVO_MT_21KH_BU_idea_FM_ThinkBook 16 G6 IRL

As already reported (#127) volume icon does not appear on panel.

In addition, going to Control Centre > Sound Preferences > Hardware > Test Speakers, clicking either front or left Test button produces no audio from the laptop speakers, nor, if plugged in, from headphones.

However, playing YouTube video in Firefox does work properly. Also working is audio playback of MP3 audio file using Celluloid.

Note that a full installation of MATE 21.3 (i.e, not 22) with kernel 6.5.0-44 (on the same laptop) has the same problem that the test does not work. However, the volume icon does show and audio from applications does play. Connecting a HDMI second screen with audio and selecting HDMI as output still does not fix the test.

MATE 22 live CD on older hardware (Asrock Z390 Pro4 motherboard, Intel CPU) still does not show volume icon, but the audio test does work.

Attached files are all for MATE 22 live CD installation for the new laptop.

[mate-22-dmesg.txt](https://github.com/user-attachments/files/16260678/mate-22-dmesg.txt)
[mate-22-hardware.txt](https://github.com/user-attachments/files/16260679/mate-22-hardware.txt)
![mate-22-sound-preferences-hardware](https://github.com/user-attachments/assets/70c56e44-e209-4e31-9fd2-bfa52ce4d10d)
![mate-22-sound-preferences-output](https://github.com/user-attachments/assets/93cfe035-2054-4c42-b6d3-a800b3dd6e25)

**Comment by clefebvre** [comment] 2024-07-17 10:32
I can't reproduce this issue.

Trying in Virtualbox, Mint 22 BETA MATE. Speaker test works fine. libcanberra packages are installed.

**Comment by oblongau** [comment] 2024-07-17 11:46
I tried MATE 22 live CD again on yet different hardware (a few years old - AMD system). No problem with the speaker test. My guess is it's something to do with (probably) very modern audio hardware that's in the laptop.

**Comment by clefebvre** [comment] 2024-07-17 12:15
It probably is.

A common source of issue for this is a missing libcanberra package but I had that checked.

If it's hardware related it's upstream from us, either in libcanberra or pipewire or even the kernel. I'll close the issue since it's not something we'll be able to fix on our end.

**Closed as completed by clefebvre** 2024-07-17 12:15 UTC
Labels: observation

**Comment by oblongau** [comment] 2024-07-20 05:55
More information that might help... All the following are Live CD running on the Lenovo laptop mentioned in the first post.

Original results from above for Sound Preferences > Hardware > Test Speakers:
Linux Mint 22 MATE beta; kernel 6.8.0-35; sound test: FAIL.

Seeing Linux Mint is built upon Ubuntu, I thought I'd try some Ubuntu Live CDs:

Ubuntu 24.04 LTS (not a "flavor"); kernel 6.8.0-31; sound test: success.
Ubuntu Cinammon 24.04; kernel 6.8.0-31; sound test: success.
Ubuntu MATE 24.04; kernel 6.8.0-31; sound test: FAIL.

So only MATE has failed. Given that some work with the same kernel, and normal audio does work, then probably not a kernel issue.

Hopefully that gives more clues.

**Comment by oblongau** [comment] 2024-07-20 10:55
Another test, which I should have thought of earlier:
Linux Mint 22 Cinnamon beta live CD; kernel 6.8.0-35; sound test: success.

**Comment by Harry-W-Haines-III** [comment] 2024-07-20 13:40
Correct.  Raptor Lake devices are better supported with the 6.8.x.xx kernel.
