### ISSUE TITLE
No animation on cursor?

### ISSUE THREAD

**Issue by Angedestenebres** [linuxmint/mint22-beta#57] opened 2024-07-02 17:58 UTC
Maybe, it's due to my VM in VirtualBox but I noticed that there is no animation on cursor (default one or xcursor), see video below:

[cinnamon-2024-07-02T194711+0200.webm](https://github.com/linuxmint/mint22-beta/assets/21110485/3b5b9a8b-e2aa-4705-a4f3-fa70958b261c)

On other VM with LMDE 6 or Mint 21.3, cursors works normally.

**Comment by JosephMcc** [comment] 2024-07-02 18:46
Can't reproduce this on my actual hardware install.

**Comment by mtwebster** [comment] 2024-07-02 20:38
Do you have guest additions installed?

Your machine graphics settings should be:
graphics controller: VMSVGA
3d acceleration: enabled
video memory: 128mb

**Comment by Angedestenebres** [comment] 2024-07-02 21:51
Hey :cat: 

> Can't reproduce this on my actual hardware install.

I guess this is linked to my VM but don't understand why.
Mainly due to the fact, I never see that before on Mint or other distributions.

> Do you have guest additions installed?
> 
> Your machine graphics settings should be: graphics controller: VMSVGA 3d acceleration: enabled video memory: 128mb

With this or not, it doesn't change anything (I can see the issue with the liveISO too). Anyway, if you are not able to reproduce that, I think this is good :)

**Comment by adrianlopezgalera** [comment] 2024-07-03 11:28
The same thing happened to me until I increased the video memory for the virtual machine. I also think it affects the speed at which themes are loaded and applied.

**Comment by clefebvre** [comment] 2024-07-04 15:17
Closing as upstream VM/rendering.

**Closed as completed by clefebvre** 2024-07-04 15:17 UTC
